### PR TITLE
License primarily under Apache 2.0 (same as Neovim)

### LINKED ISSUE #30: Please state a license
so that eg. Debian can decide whether they can package your plugin.

Thank you!

### PR DESCRIPTION
**Pull request by critiqjo**
Closes #30

I hope the contributors @ckwang and @kennykaye agrees with this. Will merge once/if both of you responds positively...

cc @phmarek

### CODE REVIEW

**Comment by kennykaye** [comment]
:+1:

**Comment by ckwang** [comment]
lgtm

**Comment by critiqjo** [comment]
Great! Thanks!

**Comment by phmarek** [comment]
Thanks a lot!

**Pull request merged**
